ALTER TABLE crawl_jobs
ADD COLUMN orchestration_phase VARCHAR(30),
ADD COLUMN selected_game_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN executed_game_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN succeeded_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN failed_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN skipped_game_count INTEGER NOT NULL DEFAULT 0;
